"""U-GAP runtime components extracted from the research implementation."""

import json

import logging

import os

import re

from src.medrag_snippet_retriever import MedRAGSnippetRetriever

class SelectedEvidenceRetriever:
    """
    Reader for evidence-centric selection JSONL files.

    Each record is expected to contain selected_evidence plus optional
    alignment_pairs/conflict_notes/query_plan fields generated by
    tools/build_evidence_pool.py.
    """

    def __init__(self, evidence_path, default_top_k=10, max_chars_per_evidence=700):
        self.evidence_path = evidence_path
        self.default_top_k = default_top_k
        self.max_chars_per_evidence = max_chars_per_evidence
        self.records = []
        self.by_index = {}
        self.by_question = {}

        if not evidence_path:
            raise ValueError("Please provide --selected_evidence_path.")
        if not os.path.exists(evidence_path):
            raise FileNotFoundError(f"Selected evidence file not found: {evidence_path}")

        self._load()
        logging.info("[SELECTED EVIDENCE] loaded=%d path=%s", len(self.records), evidence_path)

    def _load_json_or_jsonl(self):
        with open(self.evidence_path, "r", encoding="utf-8-sig") as f:
            content = f.read()

        def parse_jsonl(raw_content):
            records = []
            # str.splitlines() also splits on Unicode U+2028/U+2029. Those
            # characters may legally occur inside evidence text and splitting
            # there corrupts an otherwise valid JSONL record. JSONL records are
            # separated by the actual LF written by build_evidence_pool.py.
            for line_num, raw_line in enumerate(raw_content.split("\n"), start=1):
                line = raw_line.rstrip("\r")
                if not line.strip():
                    continue
                try:
                    records.append(json.loads(line))
                except json.JSONDecodeError as exc:
                    raise ValueError(
                        f"Invalid JSONL record in {self.evidence_path} at physical "
                        f"line {line_num}: {exc}"
                    ) from exc
            return records

        stripped = content.lstrip()
        if stripped[:1] in ("[", "{"):
            try:
                data = json.loads(content)
            except json.JSONDecodeError:
                data = parse_jsonl(content)
        else:
            data = parse_jsonl(content)

        if isinstance(data, dict):
            for key in ("data", "records", "results"):
                if isinstance(data.get(key), list):
                    return data[key]
            return [data]
        return data

    def _load(self):
        raw_records = self._load_json_or_jsonl()
        gap_records = [r for r in raw_records if isinstance(r, dict) and r.get("pipeline") == "evidence_gap_v1"]
        self.strict_gap_pipeline = bool(gap_records)
        if gap_records and len(gap_records) != len(raw_records):
            raise ValueError("Do not mix evidence-gap and legacy selected evidence records.")
        for row_num, record in enumerate(raw_records):
            if not isinstance(record, dict):
                continue
            idx = int(record.get("index", row_num))
            if self.strict_gap_pipeline and idx in self.by_index:
                raise ValueError(f"Duplicate evidence-gap question index: {idx}")
            question = record.get("question", "")
            normalized = MedRAGSnippetRetriever.normalize_question(question)
            record["index"] = idx
            self.records.append(record)
            self.by_index[idx] = record
            if normalized:
                self.by_question[normalized] = record

    def retrieve(self, query, sample_id=None, top_k=None):
        top_k = top_k or self.default_top_k
        record = None
        normalized = MedRAGSnippetRetriever.normalize_question(query)
        if getattr(self, "strict_gap_pipeline", False) and sample_id is not None:
            record = self.by_index.get(int(sample_id))
            if record is None or MedRAGSnippetRetriever.normalize_question(record.get("question", "")) != normalized:
                raise ValueError(f"Evidence-gap question/index mismatch or missing record: {sample_id}. Check benchmark and sample range.")
            if top_k < len(record.get("selected_evidence", [])):
                raise ValueError("--selected_evidence_topk would truncate the ESA evidence set.")
            return dict(record)
        if sample_id is not None:
            record = self.by_index.get(int(sample_id))
            record_question = (
                MedRAGSnippetRetriever.normalize_question(record.get("question", ""))
                if record is not None
                else ""
            )
            if record_question and normalized and record_question != normalized:
                if normalized not in record_question and record_question not in normalized:
                    logging.info(
                        "[SELECTED EVIDENCE] sample_id=%s question mismatch; falling back to text match",
                        sample_id,
                    )
                    record = None
        if record is None:
            record = self.by_question.get(normalized)
        if record is None:
            logging.info("[SELECTED EVIDENCE] no match for sample_id=%s", sample_id)
            return None

        selected = record.get("selected_evidence", []) or []
        out = dict(record)
        out["selected_evidence"] = selected[:top_k]
        return out

    def _truncate(self, text):
        text = re.sub(r"\s+", " ", str(text or "")).strip()
        if len(text) > self.max_chars_per_evidence:
            text = text[: self.max_chars_per_evidence].rsplit(" ", 1)[0] + " ..."
        return text

    def format_selected_text(self, record):
        if not record:
            return ""
        lines = []
        gap_pipeline = record.get("pipeline") == "evidence_gap_v1"
        if gap_pipeline:
            required_chars = record.get("selection_config", {}).get("evidence_chars", 0)
            if required_chars > self.max_chars_per_evidence:
                raise ValueError(
                    "Evidence-gap Answer must use --selected_evidence_max_chars >= "
                    f"{required_chars}, matching the ESA excerpts."
                )
        for ev in record.get("selected_evidence", []):
            if ev.get("evidence_type") != "text":
                continue
            eid = ev.get("evidence_id", "")
            score = ev.get("selection_score", 0.0)
            title = (ev.get("provenance", {}) or {}).get("title", "")
            content = self._truncate(ev.get("content", ""))
            prefix = f"[{eid}]"
            if gap_pipeline:
                # ESA is a soft assessment, not a medical fact or a gold answer.
                label = ev.get("esa_label", "uncertain")
                prefix += f" assessment={label}"
                lines.append(f"{prefix} {title}: {content}" if title else f"{prefix} {content}")
                continue
            if title:
                lines.append(f"{prefix} score={score:.3f} {title}: {content}")
            else:
                lines.append(f"{prefix} score={score:.3f} {content}")
        return "\n".join(lines)

    def format_selected_kg(self, record):
        if not record:
            return ""
        lines = []
        for ev in record.get("selected_evidence", []):
            if ev.get("evidence_type") != "kg":
                continue
            eid = ev.get("evidence_id", "")
            score = ev.get("selection_score", 0.0)
            prov = ev.get("provenance", {}) or {}
            pmid = prov.get("pmid", "")
            hop = prov.get("hop", "")
            supporting_text_ids = (
                ev.get("supporting_text_ids")
                or prov.get("supporting_text_ids")
                or []
            )
            content = self._truncate(ev.get("content", ""))
            meta = []
            if ev.get("evidence_subtype") == "grounded_bridge":
                meta.append("grounded_bridge")
            if supporting_text_ids:
                meta.append("supported_by=" + ",".join(str(x) for x in supporting_text_ids))
            if pmid:
                meta.append(f"PMID={pmid}")
            if hop:
                meta.append(f"hop={hop}")
            suffix = f" ({', '.join(meta)})" if meta else ""
            lines.append(f"[{eid}] score={score:.3f}{suffix} {content}")
        return "\n".join(lines)

    def format_alignment_notes(self, record, max_pairs=8):
        if not record:
            return ""
        lines = []
        pairs = record.get("prompt_alignment_pairs", record.get("alignment_pairs", [])) or []
        for pair in pairs[:max_pairs]:
            shared = ", ".join(pair.get("shared_entities", []) or [])
            label = pair.get("label", "unmatched")
            text_id = pair.get("text_evidence_id", "")
            kg_id = pair.get("kg_evidence_id", "")
            if shared:
                lines.append(f"- {text_id} and {kg_id}: {label}; shared={shared}")
            else:
                lines.append(f"- {text_id} and {kg_id}: {label}")
        return "\n".join(lines)

    def format_conflict_notes(self, record):
        if not record:
            return ""
        notes = record.get("conflict_notes", []) or []
        return "\n".join(f"- {note}" for note in notes)

    def format_adjudication_group(self, record, field):
        if not record:
            return ""
        lines = []
        for position, ev in enumerate(record.get(field, []) or [], 1):
            evidence_id = ev.get("evidence_id") or f"E{position}"
            title = (ev.get("provenance", {}) or {}).get("title", "")
            content = self._truncate(ev.get("content", ""))
            prefix = f"[{evidence_id}]"
            lines.append(f"{prefix} {title}: {content}" if title else f"{prefix} {content}")
        return "\n".join(lines)
